/**
 *
 * @author dakir3750
 */
public class Info extends javax.swing.JFrame {

    private Main menu;  //creates variable to hold a Main
    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblBalls = new javax.swing.JLabel();
        lblBalls1 = new javax.swing.JLabel();
        lblBalls2 = new javax.swing.JLabel();
        lblBalls3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblDiamond = new javax.swing.JLabel();
        lblCircle = new javax.swing.JLabel();
        lblSquare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panBackground.setBackground(new java.awt.Color(0, 0, 0));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setText("Instructions");

        lblPlayer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlayer.setForeground(new java.awt.Color(0, 0, 255));
        lblPlayer.setText("-Move Player With Arrow Keys");

        lblBalls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBalls.setForeground(new java.awt.Color(0, 0, 255));
        lblBalls.setText("-Avoid Bouncing Blue Balls");

        lblBalls1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBalls1.setForeground(new java.awt.Color(0, 0, 255));
        lblBalls1.setText("Decreases Player Size");

        lblBalls2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBalls2.setForeground(new java.awt.Color(0, 0, 255));
        lblBalls2.setText("Decreases Ball Size");

        lblBalls3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBalls3.setForeground(new java.awt.Color(0, 0, 255));
        lblBalls3.setText("Decreases Ball Speed");

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblDiamond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diamond.PNG"))); // NOI18N

        lblCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Circle.PNG"))); // NOI18N

        lblSquare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Square.PNG"))); // NOI18N

        javax.swing.GroupLayout panBackgroundLayout = new javax.swing.GroupLayout(panBackground);
        panBackground.setLayout(panBackgroundLayout);
        panBackgroundLayout.setHorizontalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiamond, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSquare, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCircle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(64, 64, 64)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addComponent(lblBalls1)
                        .addGap(34, 34, 34))
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalls3)
                            .addComponent(lblBalls2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalls)
                            .addComponent(lblPlayer)))
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBackgroundLayout.setVerticalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblPlayer)
                .addGap(18, 18, 18)
                .addComponent(lblBalls)
                .addGap(32, 32, 32)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addComponent(lblBalls1)
                        .addGap(37, 37, 37)
                        .addComponent(lblBalls2)
                        .addGap(31, 31, 31)
                        .addComponent(lblBalls3)
                        .addGap(15, 15, 15))
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addComponent(lblSquare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiamond)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCircle)
                        .addGap(3, 3, 3)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //Allows user to navigate back to main menu from instructions form
        menu = new Main();      //creates new Main
        menu.setVisible(true);  //sets the main menu visible
        this.setVisible(false); //sets the instructions form invisible
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel lblBalls;
    private javax.swing.JLabel lblBalls1;
    private javax.swing.JLabel lblBalls2;
    private javax.swing.JLabel lblBalls3;
    private javax.swing.JLabel lblCircle;
    private javax.swing.JLabel lblDiamond;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblSquare;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panBackground;
    // End of variables declaration//GEN-END:variables
}
